# name: Deploy to EC2 using SCP

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Deploy to EC2
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           EC2_HOST: ${{ secrets.EC2_HOST }}
#           EC2_USER: ${{ secrets.EC2_USER }}
#           EC2_KEY: ${{ secrets.EC2_KEY }}
#           VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
#           VITE_CLERK_PUBLISHABLE_KEY: ${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }}
#           VITE_CLERK_SIGN_UP_FORCE_REDIRECT_URL: ${{ secrets.VITE_CLERK_SIGN_UP_FORCE_REDIRECT_URL }}
#           VITE_FRONTEND_URL: ${{ secrets.VITE_FRONTEND_URL }}
#         run: |
#           echo "${{ secrets.EC2_KEY }}" | base64 --decode > ec2-key.pem
#           chmod 400 ec2-key.pem
#           echo "Trying to connect to ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} with key ec2-key.pem"

#           ssh -i ec2-key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
#             rm -rf stocky-client
#             git clone https://github.com/vic147569/stocky-client.git
#             cd /home/${{ secrets.EC2_USER }}/stocky-client
#             echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}" > .env
#             echo "VITE_CLERK_PUBLISHABLE_KEY=${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }}" >> .env
#             echo "VITE_CLERK_SIGN_UP_FORCE_REDIRECT_URL=${{ secrets.VITE_CLERK_SIGN_UP_FORCE_REDIRECT_URL }}" >> .env
#             echo "VITE_FRONTEND_URL=${{ secrets.VITE_FRONTEND_URL }}" >> .env
#             npm install
#             npm run build
#           EOF
name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Decode SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" | base64 --decode > private_key.pem
          chmod 600 private_key.pem

      - name: Set up SSH
        run: |
          eval "$(ssh-agent -s)"
          ssh-add private_key.pem

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Create remote directory if it doesn't exist
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{secrets.EC2_USER}}@${{secrets.EC2_HOST}} "sudo mkdir -p /var/www/html/ && sudo chmod -R 755 /var/www/html/"

      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i private_key.pem -r ./dist/* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/html/
