name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Decode SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" | base64 --decode > private_key.pem
          chmod 600 private_key.pem

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Fix permissions on EC2 directory
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{secrets.EC2_USER}}@${{secrets.EC2_HOST}} "sudo chmod -R 755 /var/www/html/ && sudo chown -R ubuntu:ubuntu /var/www/html/"

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i private_key.pem -r ./dist/* user@your_ec2_host:/var/www/html/
